on:
  workflow_dispatch:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build-and-scrape-site:
    name: Deploy and scrape static site
    runs-on: ubuntu-latest

    env:
      APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: NPM install
        run: |
          cd website && npm install && npm run build

      - name: Create .nojekyll file for GitHub Pages
        run: |
          touch website/build/test-site/.nojekyll

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: website/build/test-site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Docker container
        run: |
          docker run -e "APPLICATION_ID=${{ secrets.APPLICATION_ID }}" -e "API_KEY=${{ secrets.API_KEY }}" -e "CONFIG=$(cat ./algoliaConfig.json | jq -r tostring)" algolia/docsearch-scraper
